INSERT INTO users(name, email, contact_no, address, password, user_type) values('Square Hospitals Ltd.', 'square@mail', '+8809610010616', 'Nafi Tower, Level-3 (2nd floor),53 Gulshan Avenue, Gulshan-1, Dhaka-
 1212','1234', 'hospital');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Anwer Khan Modern Medical College', 'akmmc@mail.com', 'Dhanmondi, Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Aichi Hospital','aichi@mail', 'Dhaka', 'hospital', '123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Arif Memorial Hospital', 'amh@mail.com', 'Barishal', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Al Haramain Hospital', 'ahh@mail.com', 'Sylhet', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Ambia Memorial Hospital', 'amh@mail.com', 'Barisal', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('AMZ Hospital Ltd.', 'ahl@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Anwer Khan Modern Hospital Ltd', 'akmhl@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Aysha Memorial Specialised Hospital', 'amsh@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Bangladesh Neonatal Hospital', 'bnh@mail.com', 'Signboard Mor, Narayanganj', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Bangabandhu Memorial Hospital (BBMH)', 'bmh(@mail.com', 'Chittagong', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Bangabandhu Sheikh Mujib Medical University', 'bsmmu@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Bangladesh College of Nursing', 'bcon@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Bangladesh Eye Hospital Limited', 'behl@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Bangladesh Medical College Hospital', 'bmch@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Bangladesh Specialized Hospital', 'bsh@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Bangladesh Spine & Orthopaedic General Hospital Ltd', 'bs&oghl@mail.com', 'Panthapath, Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Basundhura Hospital (Pvt.) Ltd.', 'bh(l@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('BGB Hospital', 'bh@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('BIRDEM', 'birdem@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('BRB Hospital', 'brb@mail.com', 'Panthapath, Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Cardio Care Specialized and General Hospital Ltd', 'ccsaghl@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Care Hospital', 'ch@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Care Zone Hospital', 'czh@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Catharsis Medical Centre Limited', 'cmcl@mail.com', 'Gazipur', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Central Hospital', 'centralhopital@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Chander Hasi Hospital Limited', 'chhl@mail.com', 'Habiganj, Sylhet', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Chittagong Eye Infirmary and Training Hospital', 'ceiath@mail.com', 'Chittagong', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Chittagong Maa-O-Shishu Hospital', 'cmashishu@mail.com', 'Chittagong', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Chittagong Diabetic General Hospital', 'cdgh@mail.com', 'Chittagong', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Chittagong Medical College Hospital', 'cmc@mail.com', 'Chittagong', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('CMH (Combined Military Hospital)', 'cmh@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Comilla Medical College Hospital', 'cmch@mail.com', 'Comilla', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Continental Hospital Ltd.', 'chl@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Dhaka Central International Medical College Hospital', 'dcimch@mail.com', 'Adabor, Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Dhaka Community Hospital', 'dch@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Dhaka Dental College and Hospital', 'ddcah@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Dhaka Hospital', 'dh@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Dhaka Medical College & Hospital', 'dmc&h@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Dhaka National Medical College And Hospital Institute', 'dnmcahi@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Dhaka Shishu Hospital', 'dsh@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Dinajpur Medical College Hospital', 'dmch@mail.com', 'Dinajpur', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Dr. Alauddin Ahmed Clinic', 'daac@mail.com', 'Jhalakati', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Duwell Medical', 'dm@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Eastern Hospital & Medical Research Centre', 'eh&mrc@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Esperto Health Care & Research Center', 'ehcrc@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Farazy Hospital Ltd', 'fhl@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Farazy Dental Hospital & Research Center', 'fdhrc@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Gazi Medical College Hospital', 'gmch@mail.com', 'Khulna', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Genuine Cancer Hospital Limited', 'gchl@mail.com', 'Chittagong', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Gonoshasthaya Nagar Hospital', 'gnh@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Government Homeopathic Medical College Hospital', 'ghmch@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Greenland Hospital Limited', 'ghl@mail.com', 'Sector - 10, Uttara, Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Holy Family Red Crescent Medical College Hospital', 'hfrcmch@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Ibn Sina Hospital Sylhet Ltd', 'ishsl@mail.com', 'Sylhet', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Ibn Sina Hospitals', 'ish@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Institute of Child and Mother Health', 'iocamh@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Institute of Laser Surgery & Hospital', 'iolsh@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Ispahani Islamia Eye Institute and Hospital (IIEI&H)', 'iieiah(@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Japan East West Medical College Hospital', 'jewmch@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Khwaja Yunus Ali Medical College and Hospital', 'kyamcah@mail.com', 'Sirajganj', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Khulna Medical College Hospital', 'kmch@mail.com', 'Khulna', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Kumudini Hospital', 'kh@mail.com', 'Tangail', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Kuwait Bangladesh Friendship Govt. Hospital', 'kbfgh@mail.com', 'Uttara, Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Labaid Cardiac Hospital', 'lch@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Labaid Specialized Hospital', 'lsh@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Maa Nursing Home & Diagnostic Centre', 'mnhdc@mail.com', 'Tangail', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Medinova Medical Services Ltd.', 'mmsl@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('MH Samorita Hospital & Medical College', 'msh&mc@mail.com', 'Love Road, Tejgaon, Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Mikrani Dental Banasree Dhaka (Dental Hospital)', 'mdbd(h@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Mojibunnessa Eye Hospital', 'meh@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Moulana Bhasani Medical College Hospital', 'mbmch@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Mount Adora Hospital', 'mah@mail.com', 'Sylhet', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Mental Hospital', 'mh@mail.com', 'Pabna', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Mymensingh Medical College Hospital', 'mmch@mail.com', 'Mymensingh', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('National Hospital Chattagram', 'nhc@mail.com', 'Chattagram', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('National Heart Foundation', 'nhf@mail.com', 'Sylhet', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('National Institute of Cardiovascular Diseases', 'niocd@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('National Institute of Ear, Nose and Throat', 'nioenat@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('National Institute of Kidney Disease & Urology', 'niokd&u@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('National Institute of Mental Health', 'niomh@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('National Institute of Mental Health and Hospital', 'niomhah@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('National Institute of Neuroscience', 'nion@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('National Institute of Opthalmology and Hospital', 'niooah@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('National Institute of Preventive and Social Medicine', 'niopasm@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('North East Medical College and Hospital', 'nemcah@mail.com', 'Sylhet', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Nurjahan Hospital Ltd', 'nhl@mail.com', 'Sylhet', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Oasis Hospital (Pvt) Ltd', 'oh(l@mail.com', 'Sylhet', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Sylhet, M.A.G Osmani Medical College and Hospital', 'smomcah@mail.com', 'Sylhet', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Pongu Hospital Jessore', 'phj@mail.com', 'Railget, Mujib Sarak, Jessore, Bangladesh', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Popular Specialized Hospital Ltd.', 'pshl@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Rajshahi Medical College Hospital', 'rmch@mail.com', 'Rajshahi', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Rangpur Medical College Hospital', 'rmc@mail.com', 'Rangpur', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Rashmono General Hospital', 'rgh@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Royal Hospital and Research Center Ltd.', 'rharcl@mail.com', 'Chittagong', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Saint Martin Hospital', 'smh@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Samorita Hospital Ltd.', 'shl@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Shaheed Monsur Ali Medical College Hospital', 'smamch@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Shaheed Ziaur Rahman Medical College Hospital', 'szrmch@mail.com', 'Bogra', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Shalahuddin Hospital', 'sh@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Sheikh Fazilatunnessa Mujib Memorial KPJ Specialized Hospital & Nursing College', 'sfmmksh&nc@mail.com', 'Gazipur', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Sher-e-Bangla Medical College Hospital', 'smch@mail.com', 'Barisal', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Siddiqia Eye Foundation', 'sef@mail.com', 'Mymensingh', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Sir Salimullah Medical College & Mitford Hospital', 'ssmc&mh@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Sylhet Eye Hospital & Laser Centre', 'sehlc@mail.com', 'Sylhet', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Sylhet Maa O Shishu Hospital', 'smosh@mail.com', 'Sylhet', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Sylhet Medical College Hospital', 'smc@mail.com', 'Sylhet', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('The Medical College for Women and Hospital', 'tmcfwah@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Union Specialized Hospital Limited', 'ushl@mail.com', 'Aftabnagor, Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Shaheed Ahsan Ullah Master General Hospital', 'saumgh@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Shaheed Suhrawardy Medical College & Hospital', 'ssmc&h@mail.com', 'Dhaka', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Ayesha Haque Hospital', 'ahospital@mail.com', 'Beanibazar, Sylhet', 'hospital','123');
INSERT INTO users (name, email, address, user_type, password) VALUES ('Charkhai Multicare Hospital', 'charkhaih@mail.com', 'Beanibazar', 'hospital','123');